Onboarding guide tweaking
Azure/CanadaPubSecALZ pull request #51
Opened 2021-11-04 15:41 UTC by nataliakon

## Overview/Summary

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## This PR fixes/adds/changes/removes

1. *Replace me*
2. *Replace me*
3. *Replace me*

### Breaking Changes

1. *Replace me*
2. *Replace me*

## Testing Evidence

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

## As part of this Pull Request I have

- [ ] Checked for duplicate [Pull Requests](https://github.com/azure/CanadaPubSecALZ/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/azure/CanadaPubSecALZ/issues)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/azure/CanadaPubSecALZ/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated relevant and associated documentation.

2021-11-04 15:44 UTC, SenthuranSivananthan commented
@nataliakon Can you please fill out the pull request information before we start the PR review?

2021-11-04 15:49 UTC, nataliakon commented
Done :)

2021-11-05 14:00 UTC, SenthuranSivananthan requested changes

2021-11-05 16:40 UTC, SenthuranSivananthan approved these changes

2021-11-05 16:40 UTC, merged